# Generated by Django 3.0.5 on 2020-04-01 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_id', models.CharField(max_length=7)),
                ('char_code', models.CharField(max_length=3)),
                ('name', models.CharField(max_length=255)),
                ('rate', models.FloatField()),
            ],
        ),
    ]
